/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab5p2_darielsevilla;

import java.awt.Color;
import java.security.SecureRandom;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author HP
 */
public class MenuPrincipal extends javax.swing.JFrame {

    int pierdeTurno = 0;
    int pos = 0;
    SecureRandom random = new SecureRandom();
    ArrayList<Personaje> characters = new ArrayList();
    Personaje actual = new Personaje();
    DefaultMutableTreeNode nodoActual = new DefaultMutableTreeNode();
    Personaje jugador1 = new Personaje();
    Personaje jugador2 = new Personaje();

    public MenuPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crear = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_poder = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_debilidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rb_marvel = new javax.swing.JRadioButton();
        rb_dc = new javax.swing.JRadioButton();
        rb_capcom = new javax.swing.JRadioButton();
        rb_mk = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        sp_agilidadFisica = new javax.swing.JSpinner();
        sp_agilidadMental = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sp_fuerza = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sp_hp = new javax.swing.JSpinner();
        bt_add = new javax.swing.JButton();
        btg_universo = new javax.swing.ButtonGroup();
        jd_listar = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_personajes = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_listar = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        bt_exit1 = new javax.swing.JButton();
        pum_opCrud = new javax.swing.JPopupMenu();
        mi_modificar = new javax.swing.JMenuItem();
        mi_remove = new javax.swing.JMenuItem();
        jd_simulacion = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cb_player1 = new javax.swing.JComboBox<>();
        cb_player2 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_player1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_player2 = new javax.swing.JList<>();
        bt_play = new javax.swing.JButton();
        jd_juego = new javax.swing.JDialog();
        pn_juego = new javax.swing.JPanel();
        pn_p1 = new javax.swing.JPanel();
        lb_p1 = new javax.swing.JLabel();
        pn_p2 = new javax.swing.JPanel();
        lb_p2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_game = new javax.swing.JList<>();
        bt_atacar = new javax.swing.JButton();
        bt_mental = new javax.swing.JButton();
        bt_resistencia = new javax.swing.JButton();
        pn_menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_simulacion = new javax.swing.JButton();
        bt_crear = new javax.swing.JButton();
        bt_listar = new javax.swing.JButton();
        bt_exit = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CREAR");

        tf_nombre.setBackground(new java.awt.Color(255, 255, 255));
        tf_nombre.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");

        tf_poder.setBackground(new java.awt.Color(255, 255, 255));
        tf_poder.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Poder:");

        tf_debilidad.setBackground(new java.awt.Color(255, 255, 255));
        tf_debilidad.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Debilidad:");

        btg_universo.add(rb_marvel);
        rb_marvel.setForeground(new java.awt.Color(0, 0, 0));
        rb_marvel.setSelected(true);
        rb_marvel.setText("Marvel");

        btg_universo.add(rb_dc);
        rb_dc.setForeground(new java.awt.Color(0, 0, 0));
        rb_dc.setText("DC");

        btg_universo.add(rb_capcom);
        rb_capcom.setForeground(new java.awt.Color(0, 0, 0));
        rb_capcom.setText("Capcom");

        btg_universo.add(rb_mk);
        rb_mk.setForeground(new java.awt.Color(0, 0, 0));
        rb_mk.setText("MK");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Universo:");

        sp_agilidadFisica.setModel(new javax.swing.SpinnerNumberModel(100, 0, null, 1));

        sp_agilidadMental.setModel(new javax.swing.SpinnerNumberModel(100, 0, null, 1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Agilidad fisica:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Agilidad Mental:");

        sp_fuerza.setModel(new javax.swing.SpinnerNumberModel(100, null, null, 1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Fuerza:");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("HP:");

        sp_hp.setModel(new javax.swing.SpinnerNumberModel(100, 0, null, 1));

        bt_add.setText("Agregar");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tf_poder)
                                                .addComponent(tf_nombre)
                                                .addComponent(tf_debilidad, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rb_marvel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rb_dc)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rb_capcom)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rb_mk))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(sp_agilidadFisica, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                            .addComponent(sp_fuerza))
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sp_hp, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sp_agilidadMental, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_add)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_poder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_debilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_marvel)
                    .addComponent(rb_dc)
                    .addComponent(rb_capcom)
                    .addComponent(rb_mk)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_agilidadFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_agilidadMental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp_fuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(sp_hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(bt_add)
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_crearLayout = new javax.swing.GroupLayout(jd_crear.getContentPane());
        jd_crear.getContentPane().setLayout(jd_crearLayout);
        jd_crearLayout.setHorizontalGroup(
            jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_crearLayout.setVerticalGroup(
            jd_crearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personajes");
        jt_personajes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_personajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_personajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_personajes);

        jl_listar.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_listar);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Listar");

        bt_exit1.setText("Regresar");
        bt_exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_exit1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_exit1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(bt_exit1)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jd_listarLayout = new javax.swing.GroupLayout(jd_listar.getContentPane());
        jd_listar.getContentPane().setLayout(jd_listarLayout);
        jd_listarLayout.setHorizontalGroup(
            jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_listarLayout.setVerticalGroup(
            jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mi_modificar.setText("Modificar");
        mi_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_modificarActionPerformed(evt);
            }
        });
        pum_opCrud.add(mi_modificar);

        mi_remove.setText("eliminar");
        mi_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_removeActionPerformed(evt);
            }
        });
        pum_opCrud.add(mi_remove);

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Final Fight ");

        cb_player1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_player1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_player1ItemStateChanged(evt);
            }
        });
        cb_player1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cb_player1PropertyChange(evt);
            }
        });

        cb_player2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_player2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_player2ItemStateChanged(evt);
            }
        });

        jl_player1.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_player1);

        jl_player2.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jl_player2);

        bt_play.setBackground(new java.awt.Color(51, 255, 51));
        bt_play.setForeground(new java.awt.Color(0, 0, 0));
        bt_play.setText("Play");
        bt_play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_playMouseClicked(evt);
            }
        });
        bt_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_playActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(cb_player1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                    .addComponent(cb_player2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_play, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_player2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113)
                .addComponent(bt_play, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout jd_simulacionLayout = new javax.swing.GroupLayout(jd_simulacion.getContentPane());
        jd_simulacion.getContentPane().setLayout(jd_simulacionLayout);
        jd_simulacionLayout.setHorizontalGroup(
            jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_simulacionLayout.setVerticalGroup(
            jd_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_juego.setBackground(new java.awt.Color(153, 255, 255));
        pn_juego.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_p1.setBackground(new java.awt.Color(0, 204, 0));

        lb_p1.setForeground(new java.awt.Color(0, 0, 0));
        lb_p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_p1.setText("Jugador 1");

        javax.swing.GroupLayout pn_p1Layout = new javax.swing.GroupLayout(pn_p1);
        pn_p1.setLayout(pn_p1Layout);
        pn_p1Layout.setHorizontalGroup(
            pn_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_p1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_p1Layout.setVerticalGroup(
            pn_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_p1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        pn_juego.add(pn_p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 22, -1, -1));

        pn_p2.setBackground(new java.awt.Color(255, 0, 0));

        lb_p2.setForeground(new java.awt.Color(0, 0, 0));
        lb_p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_p2.setText("Jugador 2");

        javax.swing.GroupLayout pn_p2Layout = new javax.swing.GroupLayout(pn_p2);
        pn_p2.setLayout(pn_p2Layout);
        pn_p2Layout.setHorizontalGroup(
            pn_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_p2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_p2Layout.setVerticalGroup(
            pn_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_p2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        pn_juego.add(pn_p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 22, -1, -1));

        jl_game.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(jl_game);

        pn_juego.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 568, -1));

        bt_atacar.setText("Atk. fisico");
        bt_atacar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_atacarMouseClicked(evt);
            }
        });
        bt_atacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_atacarActionPerformed(evt);
            }
        });
        pn_juego.add(bt_atacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        bt_mental.setText("Atk. mental");
        bt_mental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_mentalMouseClicked(evt);
            }
        });
        pn_juego.add(bt_mental, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        bt_resistencia.setText("Resistencia");
        bt_resistencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_resistenciaMouseClicked(evt);
            }
        });
        pn_juego.add(bt_resistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        javax.swing.GroupLayout jd_juegoLayout = new javax.swing.GroupLayout(jd_juego.getContentPane());
        jd_juego.getContentPane().setLayout(jd_juegoLayout);
        jd_juegoLayout.setHorizontalGroup(
            jd_juegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_juego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_juegoLayout.setVerticalGroup(
            jd_juegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_juego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_menu.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Laboratorio N°5");

        bt_simulacion.setText("Simulación");
        bt_simulacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_simulacionMouseClicked(evt);
            }
        });

        bt_crear.setText("Crear");
        bt_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_crearMousePressed(evt);
            }
        });

        bt_listar.setText("Listar");
        bt_listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_listarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt_listarMousePressed(evt);
            }
        });

        bt_exit.setBackground(new java.awt.Color(255, 0, 0));
        bt_exit.setText("Eliminar");

        javax.swing.GroupLayout pn_menuLayout = new javax.swing.GroupLayout(pn_menu);
        pn_menu.setLayout(pn_menuLayout);
        pn_menuLayout.setHorizontalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_simulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_menuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_exit)
                .addGap(17, 17, 17))
        );
        pn_menuLayout.setVerticalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(bt_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(bt_simulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(bt_exit)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed

        String universe = "";
        if (rb_marvel.isSelected()) {
            universe = "Marvel";
        } else if (rb_dc.isSelected()) {
            universe = "DC";
        } else if (rb_capcom.isSelected()) {
            universe = "Capcom";
        } else if (rb_mk.isSelected()) {
            universe = "MK";
        }

        if (!tf_nombre.getText().equals("") && !tf_poder.getText().equals("") && !tf_debilidad.getText().equals("")) {
            String name = tf_nombre.getText();
            int repeats = 0;
            for (Personaje character : characters) {
                if (name.equals(character.getNombre())) {
                    if (pos == 0 || (pos == 1 && !actual.getNombre().equals(name))) {
                        repeats++;
                    }
                }
            }
            if (repeats > 0) {
                name += "(" + (repeats + 1) + ")";
            }
            if (pos == 0) {
                characters.add(new Personaje(name, (int) sp_agilidadFisica.getValue(), tf_poder.getText(), tf_debilidad.getText(), universe, (int) sp_agilidadMental.getValue(), (int) sp_fuerza.getValue(), (int) sp_hp.getValue()));
                JOptionPane.showMessageDialog(jd_crear, "Personaje Ingreso Exitosamente");
            } else {

                String test = actual.getUniverso();
                pos = 0;
                characters.get(characters.indexOf(actual)).setNombre(name);
                characters.get(characters.indexOf(actual)).setDebilidad(tf_debilidad.getText());
                characters.get(characters.indexOf(actual)).setUniverso(universe);
                characters.get(characters.indexOf(actual)).setAgilidadFisica((int) sp_agilidadFisica.getValue());
                characters.get(characters.indexOf(actual)).setAgilidadMental((int) sp_agilidadMental.getValue());
                characters.get(characters.indexOf(actual)).setPoder(tf_poder.getText());
                characters.get(characters.indexOf(actual)).setFuerza((int) sp_fuerza.getValue());
                characters.get(characters.indexOf(actual)).setHp((int) sp_hp.getValue());

                jd_listar.setVisible(false);
                jd_crear.setVisible(false);

            }
            tf_nombre.setText("");
            tf_poder.setText("");
            tf_debilidad.setText("");
            sp_agilidadFisica.setValue(100);
            sp_agilidadMental.setValue(100);
            sp_fuerza.setValue(100);
            sp_hp.setValue(100);

            rb_marvel.setSelected(true);
            jd_crear.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un valor en todos los campos");
        }


    }//GEN-LAST:event_bt_addActionPerformed

    private void bt_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearMouseClicked
        crudCrear();
    }//GEN-LAST:event_bt_crearMouseClicked

    private void bt_exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_exit1MouseClicked
        jd_listar.setVisible(false);
    }//GEN-LAST:event_bt_exit1MouseClicked

    private void bt_listarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_listarMouseClicked
        crudListar();        // TODO add your handling code here:
    }//GEN-LAST:event_bt_listarMouseClicked

    private void bt_crearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearMousePressed
        crudCrear();        // TODO add your handling code here:
    }//GEN-LAST:event_bt_crearMousePressed

    private void bt_listarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_listarMousePressed
        crudListar();        // TODO add your handling code here:
    }//GEN-LAST:event_bt_listarMousePressed

    private void jt_personajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_personajesMouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            DefaultListModel a = (DefaultListModel) jl_listar.getModel();

            jt_personajes.setSelectionRow(jt_personajes.getClosestRowForLocation(evt.getX(), evt.getY()));
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) jt_personajes.getSelectionPath().getLastPathComponent();
            nodoActual = node;
            String name = (String) node.getUserObject();

            int is = 0;
            for (Personaje character : characters) {
                if (name.equals(character.getNombre())) {
                    actual = character;
                    is = 2;
                    break;
                } else if (name.equals(character.getUniverso())) {
                    is = 1;

                    break;
                }
            }

            a.clear();
            if (is == 1) {

                for (int i = 0; i < node.getChildCount(); i++) {

                    for (Personaje character : characters) {
                        if (((String) ((DefaultMutableTreeNode) node.getChildAt(i)).getUserObject()).equals(character.getNombre())) {
                            actual = character;
                        }
                    }
                    a.addElement(actual);
                }
            } else if (is == 2) {

                a.addElement("Nombre -> " + actual.getNombre());
                a.addElement("HP -> " + actual.getHp());
                a.addElement("Fuerza -> " + actual.getFuerza());
                a.addElement("Poder -> " + actual.getPoder());
                a.addElement("Debilidad -> " + actual.getDebilidad());
                a.addElement("Agilidad Fisica -> " + actual.getAgilidadFisica());
                a.addElement("Agilidad Mental -> " + actual.getAgilidadMental());
                a.addElement("Universo -> " + actual.getUniverso());
                pum_opCrud.show(jt_personajes, evt.getX(), evt.getY());
            }

        }

    }//GEN-LAST:event_jt_personajesMouseClicked

    private void mi_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_modificarActionPerformed
        tf_nombre.setText(actual.getNombre());
        tf_poder.setText(actual.getPoder());
        tf_debilidad.setText(actual.getDebilidad());
        sp_fuerza.setValue(actual.getFuerza());
        sp_agilidadFisica.setValue(actual.getAgilidadFisica());
        sp_agilidadMental.setValue(actual.getAgilidadMental());
        sp_hp.setValue(actual.getHp());

        if (actual.getUniverso().equals("Marvel")) {
            rb_marvel.setSelected(true);
        } else if (actual.getUniverso().equals("DC")) {
            rb_dc.setSelected(true);
        } else if (actual.getUniverso().equals("Capcom")) {
            rb_capcom.setSelected(true);
        } else {
            rb_mk.setSelected(true);
        }
        pos = 1;
        crudCrear();


    }//GEN-LAST:event_mi_modificarActionPerformed

    private void mi_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_removeActionPerformed

        DefaultTreeModel nuevo = (DefaultTreeModel) jt_personajes.getModel();
        nuevo.removeNodeFromParent(nodoActual);
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) nuevo.getRoot();
        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (((DefaultMutableTreeNode) raiz.getChildAt(i)).getChildCount() == 0) {
                nuevo.removeNodeFromParent(((DefaultMutableTreeNode) raiz.getChildAt(i)));
            }
        }
        nuevo.reload();
    }//GEN-LAST:event_mi_removeActionPerformed

    private void bt_simulacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_simulacionMouseClicked
        finalFight();        // TODO add your handling code here:
    }//GEN-LAST:event_bt_simulacionMouseClicked

    private void cb_player1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cb_player1PropertyChange
        DefaultListModel lista = (DefaultListModel) jl_player1.getModel();
        lista.clear();
        String temp = (String) cb_player1.getSelectedItem();
        Personaje p = new Personaje();
        for (Personaje character : characters) {
            if (character.getUniverso().equals(temp)) {
                lista.addElement(character.getNombre());
            }
        }
    }//GEN-LAST:event_cb_player1PropertyChange

    private void cb_player1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_player1ItemStateChanged
        DefaultListModel lista = (DefaultListModel) jl_player1.getModel();
        lista.clear();
        String temp = (String) cb_player1.getSelectedItem();
        Personaje p = new Personaje();
        for (Personaje character : characters) {
            if (character.getUniverso().equals(temp)) {
                lista.addElement(character.getNombre());
            }
        }
    }//GEN-LAST:event_cb_player1ItemStateChanged

    private void cb_player2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_player2ItemStateChanged
        DefaultListModel lista = (DefaultListModel) jl_player2.getModel();
        lista.clear();
        String temp = (String) cb_player2.getSelectedItem();
        Personaje p = new Personaje();
        for (Personaje character : characters) {
            if (character.getUniverso().equals(temp)) {
                lista.addElement(character.getNombre());
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cb_player2ItemStateChanged

    private void bt_playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_playMouseClicked
        if (jl_player1.getSelectedIndex() != -1 && jl_player2.getSelectedIndex() != -1) {
            for (Personaje character : characters) {
                if (character.getNombre().equals(jl_player1.getSelectedValue())) {
                    jugador1 = new Personaje();
                    jugador1.setNombre(character.getNombre());
                    jugador1.setUniverso(character.getUniverso());
                    jugador1.setAgilidadFisica(character.getAgilidadFisica());
                    jugador1.setAgilidadMental(character.getAgilidadMental());
                    jugador1.setFuerza(character.getFuerza());
                    jugador1.setHp(character.getHp());
                    jugador1.setPoder(character.getPoder());
                    jugador1.setDebilidad(character.getDebilidad());
                }
            }

            for (Personaje character : characters) {
                if (character.getNombre().equals(jl_player2.getSelectedValue())) {
                    jugador2 = new Personaje();
                    jugador2.setNombre(character.getNombre());
                    jugador2.setUniverso(character.getUniverso());
                    jugador2.setAgilidadFisica(character.getAgilidadFisica());
                    jugador2.setAgilidadMental(character.getAgilidadMental());
                    jugador2.setFuerza(character.getFuerza());
                    jugador2.setHp(character.getHp());
                    jugador2.setPoder(character.getPoder());
                    jugador2.setDebilidad(character.getDebilidad());
                }

            }
            pelea();

        }
    }//GEN-LAST:event_bt_playMouseClicked

    private void bt_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_playActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_playActionPerformed

    public void pelea() {
        jd_simulacion.setVisible(false);
        jd_juego.setModal(true);
        jd_juego.pack();
        pn_p2.setVisible(false);
        pn_p1.setVisible(true);
        lb_p1.setText(jugador1.getNombre());
        lb_p2.setText(jugador2.getNombre());
        jd_juego.setLocationRelativeTo(this);
        jd_juego.setVisible(true);

        DefaultListModel m = (DefaultListModel) jl_game.getModel();
        m.clear();
    }
    private void bt_atacarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_atacarMouseClicked
        if (pn_p1.isVisible()) {
            jugador2.setHp(jugador2.getHp() - (jugador1.getAgilidadFisica() / 2));
            int rando = random.nextInt(100) + 1;
            DefaultListModel m = (DefaultListModel) jl_game.getModel();
            m.clear();
            jl_game.setForeground(Color.green);
            String resp = jugador1.getNombre() + " le quito " + (jugador1.getAgilidadFisica() / 2) + " de hp a " + jugador2.getNombre() + " con atk. fisico";
            m.addElement(resp);
            resp = "vida de " + jugador2.getNombre() + " = " + jugador2.getHp();

            m.addElement(resp);
            if (rando >= 1 && rando <= 8) {
                int oldHp = jugador1.getHp();
                jugador1.setHp(jugador1.getHp() + (jugador1.getHp() / 4));
                m.addElement(jugador1.getNombre() + " aumento su HP de " + oldHp + " a " + jugador1.getHp());
            }

            if (pierdeTurno != 1) {
                pn_p1.setVisible(false);
                pn_p2.setVisible(true);
            } else {
                pierdeTurno = 0;
            }
       
        } else {
            jugador1.setHp(jugador1.getHp() - (jugador2.getAgilidadFisica() / 2));
            int rando = random.nextInt(100) + 1;
            DefaultListModel m = (DefaultListModel) jl_game.getModel();
            m.clear();
            jl_game.setForeground(Color.red);
            String resp = jugador2.getNombre() + " le quito " + (jugador1.getAgilidadFisica() / 2) + " de hp a " + jugador1.getNombre() + " con atk. fisico";
            m.addElement(resp);
            resp = "vida de " + jugador1.getNombre() + " = " + jugador1.getHp();

            m.addElement(resp);
            if (rando >= 1 && rando <= 8) {
                int oldHp = jugador2.getHp();
                jugador2.setHp(jugador2.getHp() + (jugador2.getHp() / 4));
                m.addElement(jugador2.getNombre() + " aumento su HP de " + oldHp + " a " + jugador2.getHp());
            }

            if (pierdeTurno != 1) {
                pn_p2.setVisible(false);
                pn_p1.setVisible(true);

            } else {
                pierdeTurno = 0;
            }
           
        }

        if (jugador1.getHp() <= 0) {
            JOptionPane.showMessageDialog(null, jugador1.getNombre() + " gano!");
            jd_juego.setVisible(false);
        } else if (jugador2.getHp() <= 0) {
            JOptionPane.showMessageDialog(null, jugador2.getNombre() + " gano!");
            jd_juego.setVisible(false);
        }


    }//GEN-LAST:event_bt_atacarMouseClicked

    private void bt_atacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_atacarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_atacarActionPerformed

    private void bt_mentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_mentalMouseClicked
        if (pn_p1.isVisible()) {
            int damage = jugador1.getAgilidadMental() / 3;

            int rando = random.nextInt(100) + 1;
            if (rando >= 1 && rando <= 15) {
                damage *= 2;

            }
            jugador2.setHp(jugador2.getHp() - (jugador1.getAgilidadMental() / 3));
            DefaultListModel m = (DefaultListModel) jl_game.getModel();
            m.clear();
            jl_game.setForeground(Color.green);
            String resp = jugador1.getNombre() + " le quito " + damage + " de hp a " + jugador2.getNombre() + " con atk. mental";
            m.addElement(resp);
            if (damage == (jugador1.getAgilidadMental() / 3) * 2) {
                resp = "Oh! Golpe crítico! Its super effective!";
                m.addElement(resp);
            }
            resp = "vida de " + jugador2.getNombre() + " = " + jugador2.getHp();
            m.addElement(resp);
            if (pierdeTurno != 1) {
                pn_p1.setVisible(false);
                pn_p2.setVisible(true);
            } else {
                pierdeTurno = 0;
            }

        } else {
            int damage = jugador2.getAgilidadMental() / 3;

            int rando = random.nextInt(100) + 1;
            if (rando >= 1 && rando <= 15) {
                damage *= 2;

            }
            jugador1.setHp(jugador1.getHp() - (jugador2.getAgilidadMental() / 3));
            DefaultListModel m = (DefaultListModel) jl_game.getModel();
            m.clear();
            jl_game.setForeground(Color.red);
            String resp = jugador2.getNombre() + " le quito " + damage + " de hp a " + jugador1.getNombre() + " con atk. mental";
            m.addElement(resp);
            if (damage == (jugador2.getAgilidadMental() / 3) * 2) {
                resp = "Oh! Golpe crítico! Its super effective!";
                m.addElement(resp);
            }
            resp = "vida de " + jugador1.getNombre() + " = " + jugador1.getHp();
            m.addElement(resp);

            if (pierdeTurno != 1) {
                pn_p1.setVisible(true);
                pn_p2.setVisible(false);
            } else {
                pierdeTurno = 0;
            }
        }
        if (jugador1.getHp() <= 0) {
            JOptionPane.showMessageDialog(null, jugador1.getNombre() + " gano!");
            jd_juego.setVisible(false);
        } else if (jugador2.getHp() <= 0) {
            JOptionPane.showMessageDialog(null, jugador2.getNombre() + " gano!");
            jd_juego.setVisible(false);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_bt_mentalMouseClicked

    private void bt_resistenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_resistenciaMouseClicked
        if (pn_p1.isVisible()) {
            int oldHp = jugador1.getHp();
            jugador1.setHp(jugador1.getHp()+(int)(jugador1.getFuerza()*0.15));
            DefaultListModel m = (DefaultListModel) jl_game.getModel();
            m.clear();
            jl_game.setForeground(Color.green);
            String resp = jugador1.getNombre() + " cambio su HP de " + oldHp + " a " + jugador1.getHp();
            m.addElement( resp);
            resp = "Pero pierde el siguiente turno!";
            m.addElement(resp);
           
                pn_p1.setVisible(false);
                pn_p2.setVisible(true);
            
        } else {
            int oldHp = jugador2.getHp();
            jugador2.setHp(jugador2.getHp()+(int)(jugador2.getFuerza()*0.15));
            DefaultListModel m = (DefaultListModel) jl_game.getModel();
            m.clear();
            jl_game.setForeground(Color.red);
            String resp = jugador2.getNombre() + " cambio su HP de " + oldHp + " a " + jugador2.getHp();
            m.addElement( resp);
            resp = "Pero pierde el siguiente turno!";
            m.addElement(resp);
               
                pn_p2.setVisible(false);
                pn_p1.setVisible(true);
            
            
        }
        //este no tiene validacion porque si los 2 usan consecutivamente resistencia el siguiente q jugara es el jugador opuesto igual
        pierdeTurno = 1;
    }//GEN-LAST:event_bt_resistenciaMouseClicked

    public void crudCrear() {
        jd_crear.setModal(true);
        jd_crear.pack();
        jd_crear.setLocationRelativeTo(this);
        jd_crear.setVisible(true);
    }

    public void finalFight() {

        DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) cb_player1.getModel();
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_player2.getModel();
        modelo1.removeAllElements();
        modelo2.removeAllElements();

        for (Personaje character : characters) {
            if (modelo1.getIndexOf(character.getUniverso()) == -1) {
                modelo1.addElement(character.getUniverso());
            }
            if (modelo2.getIndexOf(character.getUniverso()) == -1) {
                modelo2.addElement(character.getUniverso());
            }
        }

        jd_simulacion.setModal(true);
        jd_simulacion.pack();
        jd_simulacion.setLocationRelativeTo(this);
        jd_simulacion.setVisible(true);

    }

    public void crudListar() {

        DefaultTreeModel m = (DefaultTreeModel) jt_personajes.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultListModel l = (DefaultListModel) jl_listar.getModel();
        l.clear();
        raiz.removeAllChildren();
        for (Personaje character : characters) {
            int isThere = 0;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (((DefaultMutableTreeNode) raiz.getChildAt(i)).getUserObject().equals(character.getUniverso())) {
                    DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(character.getNombre());
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(nodo);
                    isThere++;
                }
            }

            if (isThere == 0) {
                DefaultMutableTreeNode uni = new DefaultMutableTreeNode(character.getUniverso());
                DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(character.getNombre());
                uni.add(nodo);
                raiz.add(uni);
            }
        }
        m.reload();

        jd_listar.setModal(true);
        jd_listar.pack();
        jd_listar.setLocationRelativeTo(this);
        jd_listar.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_atacar;
    private javax.swing.JButton bt_crear;
    private javax.swing.JButton bt_exit;
    private javax.swing.JButton bt_exit1;
    private javax.swing.JButton bt_listar;
    private javax.swing.JButton bt_mental;
    private javax.swing.JButton bt_play;
    private javax.swing.JButton bt_resistencia;
    private javax.swing.JButton bt_simulacion;
    private javax.swing.ButtonGroup btg_universo;
    private javax.swing.JComboBox<String> cb_player1;
    private javax.swing.JComboBox<String> cb_player2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JDialog jd_crear;
    private javax.swing.JDialog jd_juego;
    private javax.swing.JDialog jd_listar;
    private javax.swing.JDialog jd_simulacion;
    private javax.swing.JList<String> jl_game;
    private javax.swing.JList<String> jl_listar;
    private javax.swing.JList<String> jl_player1;
    private javax.swing.JList<String> jl_player2;
    private javax.swing.JTree jt_personajes;
    private javax.swing.JLabel lb_p1;
    private javax.swing.JLabel lb_p2;
    private javax.swing.JMenuItem mi_modificar;
    private javax.swing.JMenuItem mi_remove;
    private javax.swing.JPanel pn_juego;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JPanel pn_p1;
    private javax.swing.JPanel pn_p2;
    private javax.swing.JPopupMenu pum_opCrud;
    private javax.swing.JRadioButton rb_capcom;
    private javax.swing.JRadioButton rb_dc;
    private javax.swing.JRadioButton rb_marvel;
    private javax.swing.JRadioButton rb_mk;
    private javax.swing.JSpinner sp_agilidadFisica;
    private javax.swing.JSpinner sp_agilidadMental;
    private javax.swing.JSpinner sp_fuerza;
    private javax.swing.JSpinner sp_hp;
    private javax.swing.JTextField tf_debilidad;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_poder;
    // End of variables declaration//GEN-END:variables
}
